# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Download OpenJDK 24
        run: |
          wget https://download.java.net/java/early_access/jdk24/12/GPL/openjdk-24-ea+12_linux-x64_bin.tar.gz
          tar -xzf openjdk-24-ea+12_linux-x64_bin.tar.gz
          echo "$PWD/jdk-24" >> $GITHUB_PATH
      
      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$PWD/jdk-24" >> $GITHUB_ENV
      
      - name: Verify Java Version
        run: java -version
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
